# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_visitor_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='community',
        ),
    ]
