# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_gallery_community'),
        ('tracking', '0003_remove_visitor_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_community', to='communities.Community'),
        ),
    ]
